// Mocks generated by Mockito 5.0.8 from annotations
// in movieflutter/test/presentation/pages/movie_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as i11;
import 'dart:ui' as i12;

import 'package:movieflutter/common/state_enum.dart' as i9;
import 'package:movieflutter/domain/entities/series/series.dart' as i10;
import 'package:movieflutter/domain/entities/series/series_detail.dart' as i7;
import 'package:movieflutter/domain/usecases/series/get_series_detail.dart'
    as i2;
import 'package:movieflutter/domain/usecases/series/get_series_recommendations.dart'
    as i3;
import 'package:movieflutter/domain/usecases/series/get_watchlist_series_status.dart'
    as i4;
import 'package:movieflutter/domain/usecases/series/remove_watchlist_series.dart'
    as i6;
import 'package:movieflutter/domain/usecases/series/save_watchlist_series.dart'
    as i5;
import 'package:movieflutter/presentation/provider/series/series_detail_notifier.dart'
    as i8;
import 'package:mockito/mockito.dart' as i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeGetSeriesDetail extends i1.Fake implements i2.GetSeriesDetail {}

class _FakeGetSeriesRecommendations extends i1.Fake
    implements i3.GetSeriesRecommendations {}

class _FakeGetWatchListStatus extends i1.Fake
    implements i4.GetWatchListSeriesStatus {}

class _FakeSaveWatchlist extends i1.Fake implements i5.SaveWatchlistSeries {}

class _FakeRemoveWatchlist extends i1.Fake
    implements i6.RemoveWatchlistSeries {}

class _FakeSeriesDetail extends i1.Fake implements i7.SeriesDetail {}

/// A class which mocks [MovieDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeriesDetailNotifier extends i1.Mock
    implements i8.SeriesDetailNotifier {
  MockSeriesDetailNotifier() {
    i1.throwOnMissingStub(this);
  }

  @override
  i2.GetSeriesDetail get getSeriesDetail =>
      (super.noSuchMethod(Invocation.getter(#getSeriesDetail),
          returnValue: _FakeGetSeriesDetail()) as i2.GetSeriesDetail);

  @override
  i3.GetSeriesRecommendations get getSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getSeriesRecommendations),
              returnValue: _FakeGetSeriesRecommendations())
          as i3.GetSeriesRecommendations);

  @override
  i4.GetWatchListSeriesStatus get getWatchListStatus => (super.noSuchMethod(
      Invocation.getter(#getWatchListStatus),
      returnValue: _FakeGetWatchListStatus()) as i4.GetWatchListSeriesStatus);

  @override
  i5.SaveWatchlistSeries get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
          returnValue: _FakeSaveWatchlist()) as i5.SaveWatchlistSeries);

  @override
  i6.RemoveWatchlistSeries get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
          returnValue: _FakeRemoveWatchlist()) as i6.RemoveWatchlistSeries);

  @override
  i7.SeriesDetail get series => (super.noSuchMethod(Invocation.getter(#series),
      returnValue: _FakeSeriesDetail()) as i7.SeriesDetail);

  @override
  i9.RequestState get seriesState =>
      (super.noSuchMethod(Invocation.getter(#seriesState),
          returnValue: i9.RequestState.Empty) as i9.RequestState);

  @override
  List<i10.Series> get seriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#seriesRecommendations),
          returnValue: <i10.Series>[]) as List<i10.Series>);

  @override
  i9.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: i9.RequestState.Empty) as i9.RequestState);

  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);

  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);

  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  i11.Future<void> fetchSeriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#fetchSeriesDetail, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as i11.Future<void>);

  @override
  i11.Future<void> addWatchlist(i7.SeriesDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [movie]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as i11.Future<void>);

  @override
  i11.Future<void> removeFromWatchlist(i7.SeriesDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [movie]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as i11.Future<void>);

  @override
  i11.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(Invocation.method(#loadWatchlistStatus, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as i11.Future<void>);

  @override
  void addListener(i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);

  @override
  void removeListener(i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);

  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);

  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
