// Mocks generated by Mockito 5.0.8 from annotations
// in movieflutter/test/presentation/provider/watchlist_movie_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as i4;

import 'package:dartz/dartz.dart' as i2;
import 'package:domain/entities/movie.dart' as i6;
import 'package:domain/repositories/movie_repository.dart' as i7;
import 'package:domain/usecases/get_now_playing_movies.dart';
import 'package:domain/usecases/get_popular_movies.dart';
import 'package:domain/usecases/get_top_rated_movies.dart';
import 'package:domain/usecases/get_watchlist_movies.dart';
import 'package:domain/usecases/search_movies.dart' as i3;
import 'package:domain/util/failure.dart' as i5;
import 'package:mockito/mockito.dart' as i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
class _FakeSeriesRepository extends i1.Fake implements i7.MovieRepository {}

class _FakeEither<L, R> extends i1.Fake implements i2.Either<L, R> {}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovie extends i1.Mock implements i3.SearchMovies {
  MockSearchMovie() {
    i1.throwOnMissingStub(this);
  }

  @override
  i7.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSeriesRepository()) as i7.MovieRepository);

  @override
  i4.Future<i2.Either<i5.Failure, List<i6.Movie>>> execute(String? query) =>
      (super.noSuchMethod(Invocation.method(#execute, [query]),
              returnValue: Future<i2.Either<i5.Failure, List<i6.Movie>>>.value(
                  _FakeEither<i5.Failure, List<i6.Movie>>()))
          as i4.Future<i2.Either<i5.Failure, List<i6.Movie>>>);
}

/// A class which mocks [GetPopularMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularMovie extends i1.Mock implements GetPopularMovies {
  MockGetPopularMovie() {
    i1.throwOnMissingStub(this);
  }

  @override
  i7.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSeriesRepository()) as i7.MovieRepository);

  @override
  i4.Future<i2.Either<i5.Failure, List<i6.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue: Future<i2.Either<i5.Failure, List<i6.Movie>>>.value(
                  _FakeEither<i5.Failure, List<i6.Movie>>()))
          as i4.Future<i2.Either<i5.Failure, List<i6.Movie>>>);
}

class MockGetNowPlayingMovie extends i1.Mock implements GetNowPlayingMovies {
  MockGetNowPlayingMovie() {
    i1.throwOnMissingStub(this);
  }

  @override
  i7.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSeriesRepository()) as i7.MovieRepository);

  @override
  i4.Future<i2.Either<i5.Failure, List<i6.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue: Future<i2.Either<i5.Failure, List<i6.Movie>>>.value(
                  _FakeEither<i5.Failure, List<i6.Movie>>()))
          as i4.Future<i2.Either<i5.Failure, List<i6.Movie>>>);
}

class MockGetTopRatedMovie extends i1.Mock implements GetTopRatedMovies {
  MockGetTopRatedMovie() {
    i1.throwOnMissingStub(this);
  }

  @override
  i7.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeSeriesRepository()) as i7.MovieRepository);

  @override
  i4.Future<i2.Either<i5.Failure, List<i6.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue: Future<i2.Either<i5.Failure, List<i6.Movie>>>.value(
                  _FakeEither<i5.Failure, List<i6.Movie>>()))
          as i4.Future<i2.Either<i5.Failure, List<i6.Movie>>>);
}



